//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wagner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checker {
            get {
                object obj = ResourceManager.GetObject("checker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00	82,82,82
        ///01	1,26,81
        ///02	15,15,101
        ///03	35,6,99
        ///04	54,3,75	
        ///05	64,4,38
        ///06	63,9,4
        ///07	50,19,0
        ///08	31,32,0
        ///09	11,42,0
        ///0a	0,47,0
        ///0b	0,46,10
        ///0c	0,38,45
        ///0d	0,0,0
        ///0e	0,0,0
        ///0f	0,0,0
        ///10	160,160,160
        ///11	30,74,157
        ///12	56,55,188
        ///13	88,40,184
        ///14	117,33,148
        ///15	132,35,92
        ///16	130,46,36
        ///17	111,63,0
        ///18	81,82,0
        ///19	49,99,0
        ///1a	26,107,5
        ///1b	14,105,46
        ///1c	16,92,104
        ///1d	0,0,0
        ///1e	0,0,0
        ///1f	0,0,0
        ///20	255,255,255
        ///21	0,158,255
        ///22	74,117,251
        ///23	150,102,252
        ///24	255,104,255
        ///25	253,117,181
        ///26	253,112,107
        ///27	255 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colmap_ase {
            get {
                return ResourceManager.GetString("colmap_ase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00	116,116,116
        ///01	36,24,140
        ///02	0,0,168
        ///03	68,0,156
        ///04	140,0,116
        ///05	168,0,16
        ///06	164,0,0
        ///07	124,8,0
        ///08	64,44,0
        ///09	0,68,0
        ///0a	0,80,0
        ///0b	0,60,20
        ///0c	24,60,92
        ///0d	0,0,0
        ///0e	0,0,0
        ///0f	0,0,0
        ///10	188,188,188
        ///11	0,112,236
        ///12	32,56,236
        ///13	128,0,240
        ///14	188,0,188
        ///15	228,0,88
        ///16	216,40,0
        ///17	200,76,12
        ///18	136,112,0
        ///19	0,148,0
        ///1a	0,168,0
        ///1b	0,144,56
        ///1c	0,128,136
        ///1d	0,0,0
        ///1e	0,0,0
        ///1f	0,0,0
        ///20	252,252,252
        ///21	60,188,252
        ///22	92,148,252
        ///23	204,136,252
        ///24	244,120,252
        ///25	252,116,180
        ///26	252,116,96
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colmap_fceux {
            get {
                return ResourceManager.GetString("colmap_fceux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00	102,102,102
        ///01	0,42,136
        ///02	20,18,167
        ///03	59,0,164
        ///04	92,0,126
        ///05	110,0,64
        ///06	108,6,0
        ///07	86,29,0
        ///08	51,53,0
        ///09	11,72,0
        ///0a	0,82,0
        ///0b	0,79,8
        ///0c	0,64,77
        ///0d	0,0,0
        ///0e	0,0,0
        ///0f	0,0,0
        ///10	173,173,173
        ///11	21,95,217
        ///12	66,64,255
        ///13	117,39,254
        ///14	160,26,204
        ///15	183,30,123
        ///16	181,49,32
        ///17	153,78,0
        ///18	107,109,0
        ///19	56,135,0
        ///1a	12,147,0
        ///1b	0,143,50
        ///1c	0,124,141
        ///1d	0,0,0
        ///1e	0,0,0
        ///1f	0,0,0
        ///20	255,254,255
        ///21	100,176,255
        ///22	146,144,255
        ///23	198,118,255
        ///24	243,106,255
        ///25	254,110,204
        ///26	254,12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colmap_mesen {
            get {
                return ResourceManager.GetString("colmap_mesen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00	124,124,124
        ///01	0,0,252
        ///02	0,0,188
        ///03	68,40,188
        ///04	148,0,132	
        ///05	168,0,32
        ///06	168,16,0
        ///07	136,20,0
        ///08	80,48,0
        ///09	0,120,0
        ///0a	0,104,0
        ///0b	0,88,0
        ///0c	0,64,88
        ///0d	0,0,0
        ///0e	0,0,0
        ///0f	0,0,0
        ///10	188,188,188
        ///11	0,120,248
        ///12	0,88,248
        ///13	104,68,252
        ///14	216,0,204
        ///15	228,0,88
        ///16	248,56,0
        ///17	228,92,16
        ///18	172,124,0
        ///19	0,184,0
        ///1a	0,168,0
        ///1b	0,168,68
        ///1c	0,136,136
        ///1d	0,0,0
        ///1e	0,0,0
        ///1f	0,0,0
        ///20	248,248,248
        ///21	60,188,252
        ///22	104,136,252
        ///23	152,120,248
        ///24	248,120,248
        ///25	248,88,152
        ///26	248,120,88        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colmap_theo {
            get {
                return ResourceManager.GetString("colmap_theo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00	70,69,59
        ///01	0,0,74
        ///02	0,3,112
        ///03	0,7,102
        ///04	46,0,73
        ///05	77,0,1
        ///06	76,0,0
        ///07	55,0,0
        ///08	2,0,0
        ///09	0,18,0
        ///0a	0,21,0
        ///0b	0,21,0
        ///0c	0,17,30
        ///0d	0,0,1
        ///0e	0,0,1
        ///0f	0,0,0
        ///10	180,171,157
        ///11	0,61,186
        ///12	0,44,240
        ///13	92,15,230
        ///14	165,0,173
        ///15	224,0,87
        ///16	224,6,0
        ///17	163,22,0
        ///18	97,62,0
        ///19	0,86,0
        ///1a	0,104,0
        ///1b	0,102,0
        ///1c	0,104,136
        ///1d	0,0,0
        ///1e	0,0,0
        ///1f	0,0,0
        ///20	255,255,255
        ///21	0,158,255
        ///22	74,117,251
        ///23	150,102,252
        ///24	255,104,255
        ///25	253,117,181
        ///26	253,112,107
        ///27	255,130,3
        ///28	202,155,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colmap_wiki {
            get {
                return ResourceManager.GetString("colmap_wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00	107,107,107
        ///01	0,16,132
        ///02	8,0,140
        ///03	66,0,123
        ///04	99,0,90
        ///05	107,0,16
        ///06	99,0,0
        ///07	74,49,0
        ///08	49,74,24
        ///09	0,90,33
        ///0a	33,90,16
        ///0b	8,82,66
        ///0c	0,57,115
        ///0d	0,0,0
        ///0e	0,0,0
        ///0f	0,0,0
        ///10	165,165,165
        ///11	0,66,198
        ///12	66,41,206
        ///13	107,0,189
        ///14	148,41,148
        ///15	156,16,66
        ///16	156,57,0
        ///17	140,99,33
        ///18	99,123,41
        ///19	41,140,41
        ///1a	24,148,16
        ///1b	49,132,99
        ///1c	41,115,156
        ///1d	0,0,0
        ///1e	0,0,0
        ///1f	0,0,0
        ///20	239,239,239
        ///21	90,140,255
        ///22	123,107,255
        ///23	165,90,255
        ///24	214,74,255
        ///25	231,99,156
        ///26	222,123, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string colmap_yychr {
            get {
                return ResourceManager.GetString("colmap_yychr", resourceCulture);
            }
        }
    }
}
